# Generated by Django 4.0.3 on 2022-06-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.location'),
        ),
    ]
