# Generated by Django 4.0.3 on 2022-06-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_code_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='location',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.location'),
        ),
    ]
