# Generated by Django 4.0.3 on 2022-06-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_code_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='location',
        ),
    ]
