# Generated by Django 4.0.4 on 2022-05-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('Manifest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.student'),
        ),
        migrations.AddField(
            model_name='ds_review',
            name='ds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manifest.datastructure'),
        ),
    ]
