# Generated by Django 4.0.4 on 2022-05-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Manifest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.user'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Manifest.manifest'),
        ),
    ]
