# Generated by Django 4.0.3 on 2022-05-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manifest', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='misc_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='misc_wo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='personal_wo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='techical_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='title',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='review',
            name='remark',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
