# Generated by Django 4.0.3 on 2022-05-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_shifted_student'),
        ('Manifest', '0004_alter_manifest_misc_score_alter_manifest_misc_wo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manifest.manifest'),
        ),
    ]
