# Generated by Django 4.0.3 on 2022-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manifest', '0007_remove_review_next_review_manifest_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ds_review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='next_review',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
