# Generated by Django 4.0.3 on 2022-06-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manifest', '0008_alter_datastructure_date_alter_ds_review_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='techical_score',
            new_name='technical_score',
        ),
    ]
