# Generated by Django 4.0.3 on 2022-06-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_code'),
        ('Manifest', '0009_rename_techical_score_manifest_technical_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.advisor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.reviewer'),
        ),
    ]
