# Generated by Django 4.0.3 on 2022-06-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manifest', '0010_review_advisor_alter_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastructure',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='ds_review',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='date',
            new_name='created',
        ),
    ]
