# Generated by Django 4.0.3 on 2022-06-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manifest', '0011_rename_date_datastructure_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Task Completed', 'Task Completed'), ('Need Improvement', 'Need Improvement'), ('Task Critical', 'Task Critical'), ('Repeat Review', 'Repeat Review')], default='', max_length=20),
        ),
    ]
