# Generated by Django 4.0.4 on 2022-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('UPI', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Expired', 'Expired')], max_length=10)),
                ('types', models.CharField(choices=[('CautionDeposit', 'CautionDeposit'), ('Rent', 'Rent'), ('BatchShift', 'BatchShift'), ('Upfront', 'Upfront')], max_length=20)),
            ],
        ),
    ]
