# Generated by Django 4.0.4 on 2022-06-05 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_payment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='UPI',
            new_name='upi',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
