# Generated by Django 4.0.5 on 2022-06-21 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 20, 17, 58, 6, 481167), null=True),
        ),
    ]
