# Generated by Django 4.0.4 on 2022-06-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='totalamt',
            field=models.IntegerField(default=0),
        ),
    ]
