# Generated by Django 4.0.5 on 2022-06-21 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_payment_paymentid_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 20, 17, 58, 11, 814413), null=True),
        ),
    ]
