# Generated by Django 4.0.4 on 2022-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[('---', '---'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='---', max_length=20),
        ),
    ]
