# Generated by Django 4.0.4 on 2022-06-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 27, 1, 24, 17, 269154), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='types',
            field=models.CharField(choices=[('CautionDeposit', 'CautionDeposit'), ('Rent', 'Rent'), ('BatchShift', 'BatchShift'), ('Upfront', 'Upfront'), ('Fine', 'Fine')], max_length=20),
        ),
    ]
