# Generated by Django 4.0.4 on 2022-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_alter_payment_amount_alter_payment_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
