# Generated by Django 4.0.4 on 2022-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
