# Generated by Django 4.0.4 on 2022-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_payment_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cash',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
