# Generated by Django 4.0.4 on 2022-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0012_alter_payment_cash_alter_payment_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
