<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-15 17:58
=======
# Generated by Django 4.0.3 on 2022-06-16 13:39
>>>>>>> 9667c908ac85669bf3f4495a216a0eb3e9d1655b

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0027_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
<<<<<<< HEAD
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 14, 23, 28, 28, 529531), null=True),
=======
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 15, 19, 9, 2, 22887), null=True),
>>>>>>> 9667c908ac85669bf3f4495a216a0eb3e9d1655b
        ),
    ]
