# Generated by Django 4.0.4 on 2022-05-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_initial'),
        ('User', '0001_initial'),
        ('Batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.domain'),
        ),
        migrations.AddField(
            model_name='batch',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.advisor'),
        ),
    ]
