# Generated by Django 4.0.3 on 2022-06-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_code_location'),
        ('Batch', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.location'),
        ),
    ]
