# Generated by Django 4.0.3 on 2022-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0003_batch_code_batch_created_at_batch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
