# Generated by Django 4.0.3 on 2022-05-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0004_alter_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batchno',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='location',
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
