# Generated by Django 4.0.3 on 2022-06-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_code_location'),
        ('Batch', '0004_alter_batch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.location'),
        ),
    ]
