# Generated by Django 4.0.4 on 2022-05-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Batch', '0002_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
        migrations.AddField(
            model_name='shifted',
            name='shifted_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='come_from', to='Batch.batch'),
        ),
        migrations.AddField(
            model_name='shifted',
            name='shifted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Batch.batch'),
        ),
        migrations.AddField(
            model_name='shifted',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.student'),
        ),
        migrations.AddField(
            model_name='placement',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
    ]
