# Generated by Django 4.0.4 on 2022-06-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=225, null=True)),
                ('stream', models.CharField(max_length=225, null=True)),
                ('courses', models.TextField(null=True)),
                ('backlogs', models.CharField(max_length=225, null=True)),
                ('experience', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=225, null=True)),
                ('duration', models.CharField(max_length=225, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
