# Generated by Django 4.0.4 on 2022-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_shifted_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
