# Generated by Django 4.0.3 on 2022-06-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_placement_date_alter_shifted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='shifted',
            old_name='date',
            new_name='created',
        ),
    ]
