# Generated by Django 4.0.4 on 2022-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_placement_date_alter_shifted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Training', 'Training'), ('Placed', 'Placed'), ('RequestedTermination', 'RequestedTermination'), ('Terminated', 'Terminated'), ('Quit', 'Quit')], max_length=20),
        ),
    ]
