# Generated by Django 4.0.3 on 2022-06-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_rename_date_placement_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifted',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
