# Generated by Django 4.0.4 on 2022-06-13 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0006_branch'),
        ('Student', '0006_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Batch.branch'),
        ),
    ]
