# Generated by Django 4.0.4 on 2022-06-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
