# Generated by Django 4.0.4 on 2022-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_remove_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
