# Generated by Django 4.0.4 on 2022-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_studentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(to='Student.studentcode'),
        ),
    ]
