# Generated by Django 4.0.4 on 2022-06-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
