# Generated by Django 4.0.4 on 2022-06-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_remove_attendance_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCode',
        ),
    ]
