# Generated by Django 4.0.4 on 2022-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_attendancecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='stcode',
            field=models.ManyToManyField(to='Student.attendancecode'),
        ),
    ]
