# Generated by Django 4.0.4 on 2022-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_attendance_stcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='stcode',
            field=models.ManyToManyField(to='Student.student'),
        ),
    ]
