# Generated by Django 4.0.5 on 2022-06-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_alter_attendance_stcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceCode',
        ),
    ]
