# Generated by Django 4.0.3 on 2022-06-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_shifted_status'),
        ('Student', '0016_alter_attendance_stcode'),
    ]

    operations = [
    ]
