# Generated by Django 4.0.3 on 2022-06-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_merge_20220616_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceCode',
        ),
    ]
