# Generated by Django 4.0.5 on 2022-06-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_shifted_status'),
        ('Student', '0017_delete_attendancecode'),
    ]

    operations = [
    ]
