# Generated by Django 4.0.3 on 2022-06-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_code'),
        ('Student', '0018_delete_attendancecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifted',
            name='shifted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.advisor'),
        ),
    ]
