# Generated by Django 4.0.3 on 2022-06-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_shifted_shifted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifted',
            old_name='shifted_in',
            new_name='shifted_from',
        ),
    ]
