# Generated by Django 4.0.3 on 2022-06-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_rename_shifted_in_shifted_shifted_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifted',
            name='shifted_by',
        ),
    ]
