# Generated by Django 4.0.3 on 2022-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_profile_dob_alter_profile_govtid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='Profile/defaultProPic.png', upload_to='Media/Profile'),
        ),
    ]
