# Generated by Django 4.0.4 on 2022-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Placement', 'Placement'), ('AdvisorChange', 'Advisor Change'), ('BatchShift', 'Batch Shift'), ('Termination', 'Termination')], max_length=20),
        ),
    ]
