# Generated by Django 4.0.4 on 2022-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Placement', 'Placement'), ('AdvisorChange', 'Advisor Change'), ('BatchShift', 'Batch Shift'), ('Termination', 'Termination'), ('Message', 'Message')], max_length=20),
        ),
    ]
