# Generated by Django 4.0.3 on 2022-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_profile_father_profile_father_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Student', 'Student'), ('Advisor', 'Advisor'), ('Accounts', 'Accounts'), ('Placement', 'Placement'), ('Lead', 'Lead')], max_length=20),
        ),
    ]
