# Generated by Django 4.0.4 on 2022-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
