# Generated by Django 4.0.3 on 2022-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Advisor', 'Advisor'), ('Communication', 'Communication'), ('Finance', 'Finance'), ('Lead', 'Lead'), ('Placement', 'Placement'), ('Student', 'Student')], max_length=20),
        ),
    ]
