# Generated by Django 4.0.3 on 2022-06-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created',
        ),
    ]
