# Generated by Django 4.0.3 on 2022-06-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_notification_creator'),
        ('User', '0013_rename_date_notification_created'),
    ]

    operations = [
    ]
