# Generated by Django 4.0.3 on 2022-06-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='domain',
        ),
    ]
