# Generated by Django 4.0.3 on 2022-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_profile_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/da3qthae5/image/upload/v1655698734/my%20files/hus89vdrrn2mzxxi6xo8.jpg', max_length=200, null=True),
        ),
    ]
