# Generated by Django 4.0.3 on 2022-06-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_profile_public_id_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
