# Generated by Django 4.0.3 on 2022-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_profile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
